### PR TITLE
handle case were err.code is a string

### PR DESCRIPTION
**Pull request by jkroso**
as it can be in node.js

### CODE REVIEW

**Comment by DylanPiercey** [comment]
Do you think it would be better to just cast status to a string/number?

**Comment by jkroso** [comment]
No it's stuff like "ECONNREFUSED"

**Comment by jkroso** [comment]
Ok now it looks about right.

image

**Comment by jkroso** [comment]
Its some other middleware that's logging the error's stack there but should it be in this middleware?

**Comment by DylanPiercey** [comment]
Currently errors are caught and logged in rill itself here https://github.com/rill-js/rill/blob/master/src/index.js#L66. I'd consider changing this but it seems like the alternative would be letting the promises silently swallow the errors. This PR looks okay though.

@jkroso So when exactly does node set a status like this? I haven't seemed to come across it. Do you have an example?

**Comment by jkroso** [comment]
Oh yup I must of been catching the errors somewhere then. I think any errors that make it out of the middleware stack should kill the process rather than log and carry on but it doesn't matter since all errors should be dealt with by middleware anyway

Example:

``` js
fs.readFile('sads',function(r){console.log(r.code)})
```

**Comment by DylanPiercey** [comment]
Ah ic. So your doing stuff like:

``` javascript
const fs = require("mz/fs");
app.get("/...", ({ res })=> {
    // fs error will be in rill promise chain.
    return fs.readFile("sads")
        .then(...);
});
```

Typically I just use "ctx.assert" to test for errors and provide a better error message but I think accounting for this case would be good.

**Pull request merged**
